# Ezt én írtam

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Login:index }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:admin }

logout:
    path:     /logout
    defaults: { _controller: AppBundle:Login:logout }

new_debt:
    path:     /new
    defaults: { _controller: AppBundle:Default:newDebt }

delete_debt:
    path:     /delete
    defaults: { _controller: AppBundle:Default:deleteDebt }

completed:
    path:     /completed
    defaults: { _controller: AppBundle:Default:completed }